### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by maz2331** [marcosbozzani/Win10ActiveHours#3]
I assure you I am running powershell as an admin. I've even tried domain admin.
I keep getting the following and I am not sure why.
PS D:\> .\setup.ps1
Register-ScheduledTask : Access is denied.
At D:\setup.ps1:63 char:5
+     Register-ScheduledTask $TaskName $TaskPath @options | Out-Null
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (PS_ScheduledTask:Root/Microsoft/...S_ScheduledTask) [Register-Schedul
   edTask], CimException
    + FullyQualifiedErrorId : HRESULT 0x80070005,Register-ScheduledTask

**Comment by marcosbozzani** [comment]
Could you try to replace the line 63 of the setup.ps1 with the following code, run it again and post the output?
```powershell
echo $TaskName $TaskPath @options
Register-ScheduledTask $TaskName $TaskPath @options
```

**Comment by maz2331** [comment]
Thank you I really appreciate the help.

PS D:\> .\setup.ps1
Update
\Win10ActiveHours\
-Principal:


DisplayName         :
GroupId             :
Id                  :
LogonType           : S4U
RunLevel            : Limited
UserId              : paul
ProcessTokenSidType : Default
RequiredPrivilege   :
PSComputerName      :

-Trigger:
Enabled            : True
EndBoundary        :
ExecutionTimeLimit :
Id                 :
Repetition         :
StartBoundary      :
Delay              :
Subscription       : <QueryList><Query Id="0" Path="System"><Select
Path="System">*[System[Provider[@Name='Microsoft-Windows-Power-Troubleshooter'] 
and
EventID=1]]</Select></Query></QueryList>
ValueQueries       :
PSComputerName     :

Enabled            : True
EndBoundary        :
ExecutionTimeLimit :
Id                 :
Repetition         :
StartBoundary      :
Delay              :
PSComputerName     :

Enabled            : True
EndBoundary        :
ExecutionTimeLimit :
Id                 :
Repetition         :
StartBoundary      : 2020-02-07T11:00:00Z
DaysInterval       : 1
RandomDelay        :
PSComputerName     :

Enabled            : True
EndBoundary        :
ExecutionTimeLimit :
Id                 :
Repetition         :
StartBoundary      : 2020-02-07T23:00:00Z
DaysInterval       : 1
RandomDelay        :
PSComputerName     :

-Force:
True
-Action:
Id               :
Arguments        : -NoLogo -NonInteractive -WindowStyle Hidden 
-EncodedCommand CgAgACAAIAAgACQAawBlAHkAIAA9ACAAIgBIAEsA
TABNADoAXABTAE8ARgBUAFcAQQBSAEUAXABNAGkAYwByAG8AcwBvAGYAdABcAFcAaQBuAGQAbwB3AHMAVQBwAGQAYQB0AGUAXABV
AFgAXABTAGUAdAB0AGkAbgBnAHMAIgAKACAAIAAgACAAJABoAG8AdQByACAAPQAgACgAZwBlAHQALQBkAGEAdABlACkALgBoAG8A
dQByAAoAIAAgACAAIABpAGYAIAAoACQAaABvAHUAcgAgAC0AZwBlACAAMQA4ACAALQBvAHIAIAAkAGgAbwB1AHIAIAAtAGwAdAAg
ADYAKQAgAHsACgAgACAAIAAgACAAIAAgACAAUwBlAHQALQBJAHQAZQBtAFAAcgBvAHAAZQByAHQAeQAgACQAawBlAHkAIABBAGMA
dABpAHYAZQBIAG8AdQByAHMAUwB0AGEAcgB0ACAAMQA4AAoAIAAgACAAIAAgACAAIAAgAFMAZQB0AC0ASQB0AGUAbQBQAHIAbwBw
AGUAcgB0AHkAIAAkAGsAZQB5ACAAQQBjAHQAaQB2AGUASABvAHUAcgBzAEUAbgBkACAAMQAyAAoAIAAgACAAIAB9ACAACgAgACAA
IAAgAGUAbABzAGUAIAB7AAoAIAAgACAAIAAgACAAIAAgAFMAZQB0AC0ASQB0AGUAbQBQAHIAbwBwAGUAcgB0AHkAIAAkAGsAZQB5
ACAAQQBjAHQAaQB2AGUASABvAHUAcgBzAFMAdABhAHIAdAAgADYACgAgACAAIAAgACAAIAAgACAAUwBlAHQALQBJAHQAZQBtAFAA
cgBvAHAAZQByAHQAeQAgACQAawBlAHkAIABBAGMAdABpAHYAZQBIAG8AdQByAHMARQBuAGQAIAAwAAoAIAAgACAAIAB9AAoAIAAg
ACAAIABTAGUAdAAtAEkAdABlAG0AUAByAG8AcABlAHIAdAB5ACAAJABrAGUAeQAgAEkAcwBBAGMAdABpAHYAZQBIAG8AdQByAHMA
                    RQBuAGEAYgBsAGUAZAAgADEACgA=
Execute          : powershell
WorkingDirectory :
PSComputerName   :

-Settings:
AllowDemandStart                : True
AllowHardTerminate              : True
Compatibility                   : Win7
DeleteExpiredTaskAfter          :
DisallowStartIfOnBatteries      : False
Enabled                         : True
ExecutionTimeLimit              : PT72H
Hidden                          : False
IdleSettings                    : MSFT_TaskIdleSettings
MultipleInstances               : IgnoreNew
NetworkSettings                 : MSFT_TaskNetworkSettings
Priority                        : 7
RestartCount                    : 0
RestartInterval                 :
RunOnlyIfIdle                   : False
RunOnlyIfNetworkAvailable       : False
StartWhenAvailable              : True
StopIfGoingOnBatteries          : False
WakeToRun                       : True
DisallowStartOnRemoteAppSession : False
UseUnifiedSchedulingEngine      : True
MaintenanceSettings             :
volatile                        : False
PSComputerName                  :

Register-ScheduledTask : Access is denied.
At D:\setup.ps1:64 char:2
+     Register-ScheduledTask $TaskName $TaskPath @options
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : PermissionDenied: 
(PS_ScheduledTask:Root/Microsoft/...S_ScheduledTask) [Register-Schedul
    edTask], CimException
     + FullyQualifiedErrorId : HRESULT 0x80070005,Register-ScheduledTask

\Win10ActiveHours\Update installed
\Win10ActiveHours\Update not found

**Comment by marcosbozzani** [comment]
Try to replace lines 47, 48 and 49:

```powershell
Principal = New-ScheduledTaskPrincipal `
            -UserId $env:USERNAME `
            -LogonType S4U
```

with:

```powershell
Principal = New-ScheduledTaskPrincipal -UserId "LOCALSERVICE" -LogonType ServiceAccount -RunLevel Highest
```

and see if it works.

**Comment by maz2331** [comment]
that did it. thanks man you are awesome.
send me your paypal address so I can send you something for a couple drinks.

**Comment by marcosbozzani** [comment]
My paypal address is marcosbozzani@gmail.com
I've incorporated this fix in this commit: https://github.com/marcosbozzani/Win10ActiveHours/commit/7a214576ee2681c3e677b6c017429934a2c8c7d2
